### ISSUE TITLE
test-godaddy-debian8-x64-3.adoptopenjdk.net not properly configured?

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-infrastructure#1145] opened 2020-02-14 14:56 UTC
I'm seeing some test failures which look like test system setup issues:

```
test-godaddy-debian8-x64-3.adoptopenjdk.net: test-godaddy-debian8-x64-3.adoptopenjdk.net: Name or service not known
```

See:
https://ci.adoptopenjdk.net/view/Test_upstream/job/Test_openjdk11_hs_sanity.openjdk_x86-64_linux_upstream/36/testReport/junit/java_net_DatagramPacket_Constructor/java/Constructor/
https://ci.adoptopenjdk.net/view/Test_upstream/job/Test_openjdk11_hs_sanity.openjdk_x86-64_linux_upstream/36

Looks like a similar/same issue to #1134.

**Comment by sxa555** [comment] 2020-02-18 17:56
GoDaddy Debian machines disabled by @smlambert

**Comment by adam-thorpe** [comment] 2020-02-19 10:01
@sxa555 Can we add test-godaddy-ubuntu1604-x64-1 and 3 to this list and disable those too? Reporting similar failures. 2 and 4 are already offline

**Comment by lumpfish** [comment] 2020-02-19 11:52
Some system tests fail due to this configuration error too.  Messages like:
```
10:14:24  LT  Test failed:
10:14:24  LT  java.net.UnknownHostException: test-godaddy-ubuntu1604-x64-3.adoptopenjdk.net: test-godaddy-ubuntu1604-x64-3.adoptopenjdk.net: Name or service not known
10:14:24  LT  	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1632)
10:14:24  LT  	at gnu.testlet.java.net.DatagramPacket.DatagramPacketTest2.<init>(DatagramPacketTest2.java:70)
10:14:24  LT  	at java.base/java.lang.J9VMInternals.newInstanceImpl(Native Method)
10:14:24  LT  	at java.base/java.lang.Class.newInstance(Class.java:2089)
10:14:24  LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:52)
10:14:24  LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
10:14:24  LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
10:14:24  LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
10:14:24  LT  	at java.base/java.lang.Thread.run(Thread.java:835)
10:14:24  LT  Caused by: java.net.UnknownHostException: test-godaddy-ubuntu1604-x64-3.adoptopenjdk.net: Name or service not known
10:14:24  LT  	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
10:14:24  LT  	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932)
10:14:24  LT  	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1505)
10:14:24  LT  	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851)
10:14:24  LT  	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1495)
10:14:24  LT  	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1627)
10:14:24  LT  	... 8 more
10:14:24  LT  <<<
```

**Comment by sxa555** [comment] 2020-02-21 16:08
> @sxa555 Can we add test-godaddy-ubuntu1604-x64-1 and 3 to this list and disable those too? Reporting similar failures. 2 and 4 are already offline

Done

**Comment by sxa555** [comment] 2020-02-21 17:57
Side note to the above - `test-godaddy-ubuntu1604-1` in particular seems to have performance issues (potentailly caused by timeouts of course) based on https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1165

**Comment by M-Davies** [comment] 2020-04-27 13:10
This is still affecting `test-godaddy-debian8-x64-4.adoptopenjdk.net`. See https://github.com/AdoptOpenJDK/openjdk-tests/issues/1750#issuecomment-619974621

**Comment by jerboaa** [comment] 2020-05-13 08:55
@sxa We are seeing issues for `test-godaddy-
> ubuntu1604-x64-4.adoptopenjdk.net`. Same as https://github.com/AdoptOpenJDK/openjdk-tests/issues/1750#issuecomment-619974621 Failures are:
```
java.net.UnknownHostException: test-godaddy-ubuntu1604-x64-4.adoptopenjdk.net: test-godaddy-ubuntu1604-x64-4.adoptopenjdk.net: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
	at BadHandshakeTest.main(BadHandshakeTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: test-godaddy-ubuntu1604-x64-4.adoptopenjdk.net: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
	... 7 more
```

**Comment by jerboaa** [comment] 2020-05-13 08:56
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_linux_upstream/42/

**Comment by M-Davies** [comment] 2020-05-13 10:20
@jerboaa Those test failures are being excluded in https://github.com/AdoptOpenJDK/openjdk-tests/pull/1785 after triaging in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1750

**Comment by jerboaa** [comment] 2020-05-13 19:30
@M-Davies Sure, but they work fine on a properly configured system. Shame they need to be excluded because of this.

**Comment by smlambert** [comment] 2020-05-13 20:25
Either the tests need to be temporarily excluded until the machine config can be corrected **or** this machine needs to be removed from the test role (remove ci.role.test label) until the machine config can be corrected, so that we do not keep hitting it and failing the tests.  I am fine with either approach.

**Comment by sxa** [comment] 2020-05-18 16:48
Marked [godaddy-ubuntu-4](https://ci.adoptopenjdk.net/computer/test-godaddy-ubuntu1604-x64-4/) offline as per Severin's comment ... If people wouldn't dump machines live into my infrastructure and then ignore failures that would be the best way to keep things stable...

**Comment by Willsparker** [comment] 2020-07-06 15:00
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1423#issuecomment-654241669 
I managed to find a solution to an issue that has the same error message as listed here, therefore it's worth trying to apply the fix to the other GoDaddy machines and see if the tests that were excluded now run on them.
For the sake of these, I'm going to just use the `com/sun/jdi/BadHandshakeTest.java` test that was excluded with https://github.com/AdoptOpenJDK/openjdk-tests/pull/1785

| Machine          | Grinder Run | Pass? |
|------------------|-------------|-------|
| ubuntu1604-x64-1 |    Offline currently    |       |
| ubuntu1604-x64-2 |  3518  |  yes     |
| ubuntu1604-x64-3 |  3519  |  yes     |
| ubuntu1604-x64-4 |   3520 |  yes     |
| debian8-x64-1    |   Fix not applied yet   |       |
| debian8-x64-2    |   Fix not applied yet   |       |
| debian8-x64-3    |   Fix not applied yet   |       |
| debian8-x64-4    |   Fix not applied yet   |       |

**Comment by M-Davies** [comment] 2020-07-07 08:28
PR is in to do that here: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1870

**Comment by Willsparker** [comment] 2020-07-07 13:16
With the above PR merged, I think this can be closed now.

**Closed by Willsparker** 2020-07-07 13:16 UTC
Labels: bug, godaddy
