### ISSUE TITLE
test-softlayer-ubuntu1604-x64-1 missing suitable ssh-agent provider

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#684] opened 2019-01-24 03:25 UTC
I have disabled the test-softlayer-ubuntu1604-x64-1 machine, as testing is not even able to start due to this error, that just started occurring today.

https://ci.adoptopenjdk.net/view/Test_external/job/openjdk11_j9_externaltest_x86-64_linux/108/console

$ ssh-agent
20:49:36 [ssh-agent] FATAL: Could not find a suitable ssh-agent provider
20:49:36 [ssh-agent] Diagnostic report
20:49:36 [ssh-agent] * Exec ssh-agent (binary ssh-agent on a remote machine)
20:49:36 [ssh-agent]     hudson.AbortException: Failed to run ssh-agent
20:49:36 [ssh-agent]     	at com.cloudbees.jenkins.plugins.sshagent.exec.ExecRemoteAgent.<init>(ExecRemoteAgent.java:71)

**Comment by sxa555** [comment] 2019-01-24 12:09
Looks to be out of disk space on `/` which is likely the cause of everything that's failing on that machine ... Investigating

**Comment by sxa555** [comment] 2019-01-24 12:47
`/var/lib/docker` is 19Gb and taking up most of the file system ... Admittedly it's not a particularly large filesystem at 24Gb:
```
root@test-softlayer-ubuntu1604-x64-1:/var/lib/docker# docker images
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
adoptopenjdk-wildfly-test         latest              702ab1362271        38 hours ago        1.1GB
adoptopenjdk-tomcat-test          latest              695f3b13be4b        38 hours ago        1.23GB
adoptopenjdk-thorntail-mp-tck     latest              c6411a50edb8        38 hours ago        1.16GB
adoptopenjdk-scala-test           latest              0d55422b259f        38 hours ago        966MB
adoptopenjdk-payara-mp-tck        latest              78907b651c4f        38 hours ago        1.31GB
adoptopenjdk-openliberty-mp-tck   latest              6e81efe5109e        38 hours ago        1.68GB
adoptopenjdk-lucene-solr-test     latest              bd9478ea0264        38 hours ago        1.84GB
adoptopenjdk-kafka-test           latest              9a7cc973acf7        38 hours ago        1.02GB
adoptopenjdk-jenkins-test         latest              f1f84af6a7a4        38 hours ago        983MB
adoptopenjdk-functional-test      latest              11ea8babeab0        38 hours ago        1.22GB
adoptopenjdk-example-test         latest              1944d71b55fa        38 hours ago        813MB
adoptopenjdk-elasticsearch-test   latest              9cc73a25889d        38 hours ago        3.24GB
adoptopenjdk-derby-test           latest              36c6a3e42614        38 hours ago        813MB
adoptopenjdk/openjdk11-openj9     latest              c102997bf611        42 hours ago        431MB
<none>                            <none>              5744f7c89c49        3 weeks ago         1.71GB
root@test-softlayer-ubuntu1604-x64-1:/var/lib/docker# 
```

**Comment by sxa555** [comment] 2019-01-24 12:55
Saying that, there's another 25Gb filesystem in `/home` ... Might be worth adding another FS mounted at `/var/lib/docker` ... FYI @tellison

**Comment by tellison** [comment] 2019-01-24 16:11
Added a third disk of 40Gb.  Mount that as required.

**Comment by sxa555** [comment] 2019-01-24 17:33
Done as /var/lib/docker and rsync'd the original directory across (Original files retained as /var/lib/docker-root and also as a tarball in the new filesystem)

**Comment by sxa555** [comment] 2019-01-24 17:34
https://ci.adoptopenjdk.net/job/Grinder/905/console now running on the machine

**Comment by smlambert** [comment] 2019-01-24 17:45
Thanks to you both @sxa555 @tellison ! 

For the record, we will break out all of those tests to run in separate Jenkins jobs instead of all in a single job.  The jobs do clean up after themselves, but not until the end, so at peak, all containers are present.  

Shortly 'all' should equal '1', instead of 14 at a time.

**Comment by sxa555** [comment] 2019-01-24 17:48
Job completed ok - closing issue.

**Closed by sxa555** 2019-01-24 17:48 UTC
Labels: bug
