### ISSUE TITLE
Godaddy debian8 machines setup issue

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-infrastructure#1134] opened 2020-02-11 10:22 UTC
test-godaddy-debian8-x64-(1-4)

```
Execution failed: `main' threw exception: java.net.UnknownHostException: test-godaddy-debian8-x64-4.adoptopenjdk.net: test-godaddy-debian8-x64-4.adoptopenjdk.net: Name or service not known
```

**Comment by karianna** [comment] 2020-02-12 03:19
@gdams - I'm going to hazard a guess that you might know what to do here.

**Comment by sxa555** [comment] 2020-02-18 17:56
GoDaddy Debian machines disabled by @smlambert

**Comment by sxa555** [comment] 2020-02-21 16:06
Duplicate of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1145

**Closed by sxa555** 2020-02-21 16:06 UTC
Labels: bug, godaddy
