### ISSUE TITLE
Ensure machines configured with enough mapped shared memory

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#840] opened 2019-07-22 20:55 UTC
Noted during the most recent release, SharedClassesAPI failure (an extended.system test) is due to a machine config issue (memory mapped shared memory should get [increased](https://stackoverflow.com/questions/2017004/setting-shmmax-etc-values-on-mac-os-x-10-6-for-postgresql)).  

See https://github.com/AdoptOpenJDK/TSC/issues/99#issuecomment-513042506 for links to failures (noted on machines test-macincloud-macos1014-x64-2, test-macincloud-macos1013-x64-2 though there could be others).

**Comment by smlambert** [comment] 2019-07-24 02:11
I do not know the details, @pshipton mentioned it, and said the openj9 machines were with plenty of shared memory space.  Let's get the details from him.  I would hope we can attempt to keep the configuration of machines across the projects to be aligned, this detail must not be captured anywhere in doc or playbooks to date.

**Comment by pshipton** [comment] 2019-07-24 03:53
Check with @jdekonin for the setting of SHMMAX on the OpenJ9 Mac machines.

**Comment by pshipton** [comment] 2019-07-24 03:54
Or isn't there some older Mac machines that were working? Compare the SHMMAX setting with the new machines.

**Comment by jdekonin** [comment] 2019-07-24 12:50
The settings in sysctl.conf I was asked to make were : 
kern.sysv.shmmax=125839605760
kern.sysv.shmall=30722560

This is documented in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/212

**Comment by sxa555** [comment] 2019-07-30 19:39
@gdams Can you cover this in the macos playbooks?

**Comment by sxa555** [comment] 2019-08-26 18:55
Going to close this now it's been merged. If the problem is still there please reopen

**Closed by sxa555** 2019-08-26 18:55 UTC
Labels: aix
