### ISSUE TITLE
We do not currently have any sles12 s390x machines tagged with "test"

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#25] opened 2017-09-28 16:03 UTC
At the moment we run the systemtests on `sles12` as this has a suitable version of the `libffi` library available (https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/19). At present none of those machines has a a tag of `test` so I cannot use that tag to run the systemtest jobs. If I leave the tag off I end up with things potentially running on `master` which doesn't work well at all as it doesn't have `make` installed. I could use `build` that would stop the other platforms from using the dedicated test machines, so that's not a sensible solutionest either. For now I've set the jobs to use `!hg` which knocks out three machines including `master` and is adequate until we get a `sles12/s390x` box tagged with `test`

See also the work item about machines tags: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/93

**Comment by karianna** [comment] 2017-09-28 16:35
@gdams We just need a new box right?

**Comment by gdams** [comment] 2017-10-03 11:39
@karianna getting a "new" box on s390x can be slightly difficult ;) I'm happy to look at splitting the boxes between build and test

**Comment by karianna** [comment] 2017-10-03 14:14
@gdams - We can (and should) timeshare the rarer boxes but if we can source more of them that would be good in the long term as we'll be building and testing so many different versions (every 6 months a new release).

**Comment by sxa555** [comment] 2017-10-03 16:32
Yep obviously happy to share, but at the moment I think there's only the one zlinux box that can run the executables we produce so it could become a bottleneck

**Comment by gdams** [comment] 2017-10-18 15:13
@sxa555 are the Ubuntu boxes not going to work then? I was under the impression that we were now building openjdk binaries using Ubuntu 16.04?

**Comment by sxa555** [comment] 2017-11-30 14:22
Doesn't work out of the box on 16.04, no - it still looks for libffi.so.4 whereas Ubuntu 16.04 has libffi.so.6.0.4. IIRC you can symlink them together and get it working but that's probably not the sensible option.

**Comment by smlambert** [comment] 2017-12-11 14:59
Apologies, I had not even seen this issue (prior to creating #85).  @tellison if you like, you can close 85 as a duplicate.

**Comment by sxa555** [comment] 2018-01-17 16:26
Looks like we've got most of the builds moved off SLES12 but https://ci.adoptopenjdk.net/job/openjdk9_build_s390x_linux/ is still running on it - do we know if that's intentional or an oversight? Would be good to move this one forward - at the moment we have three Ubu build machines and this SLES12 one - presumably one of these could be allocated as a dedicated test system now?

**Comment by gdams** [comment] 2018-01-17 17:01
I assume that it perhaps has a different compiler level on it? I'll investigate

**Comment by smlambert** [comment] 2018-01-24 18:13
We have created test builds for this platform, but they are currently disabled as there are no s390x machines for test.  See this spreadsheet for which test builds are disabled due to no test machines available: https://docs.google.com/spreadsheets/d/1X4CCfvMoCgEavRbvejHrTvPnqj37MB-_C6LB6b8Akkc/edit?usp=sharing

**Comment by smlambert** [comment] 2018-03-09 20:31
I have added a note on [tests/309](https://github.com/AdoptOpenJDK/openjdk-tests/issues/309), that we are unable to run system or openjdk_regression tests against the openjdk8-openj9 release 0.8 candidate build for s390x_linux at this time as we do not have a test machine for this platform.

**Comment by gdams** [comment] 2018-03-11 13:12
@smlambert you do now :) https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-1/

**Comment by smlambert** [comment] 2018-03-11 15:04
Awesome! thanks @gdams

**Comment by gdams** [comment] 2018-03-11 18:13
closing issue for now

**Closed by gdams** 2018-03-11 18:13 UTC
Labels: Infra Request, zlinux

**Comment by sxa555** [comment] 2018-03-16 17:07
The OpenJ9 are happy on there although our latest released HotSpot build does not. Somewhat worrying it would appear that the HotSpot (Or zero!) VM crashes when you try to run it on that Ubuntu machine at the moment. That'll probably need another issue raised ...
