### ISSUE TITLE
Installer job failed for jdk11u-mac-x64

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1382] opened 2020-06-11 08:40 UTC
jdk11u-mac-x64-hotspot
jdk11u-mac-x64-openj9

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-hotspot/579/console

`07:35:58  Execution error: null`

**Comment by gdams** [comment] 2020-06-11 09:50
This error is caused by:

```
security: SecKeychainUnlock <NULL>: The user name or passphrase you entered is not correct.
Build step 'Execute shell' marked build as failure
```

Essentially the machine is trying to unlock the keychain and is complaining that the password is incorrect. I've rebooted the machine which fixed the issue (I've had the same issue in the past)

The only thing I can think is that it's because the machine had 2 executors and was trying to codesign 2 binaries at the same time.

Closing for now to see if this fixes things

**Comment by andrew-m-leonard** [comment] 2020-09-02 08:36
Problem has re-coccured: https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_mac/4563/console
```
Copied 3 artifacts from "build-scripts » jobs » jdk » jdk-mac-x64-hotspot" build number 232
[create_installer_mac] $ /bin/sh -xe /var/folders/rt/8_by_h8n5g9d5jhp66cf_7d80000gr/T/jenkins3652285145151103538.sh
+ bash pkgbuild/create-installer-mac.sh
security: SecKeychainUnlock <NULL>: The user name or passphrase you entered is not correct.
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE
```
Machine: test-macincloud-macos1014-x64-1
@gdams

**Comment by Willsparker** [comment] 2020-09-08 09:11
Looking at it now, the specific machine is `test-macincloud-macos1014-x64-1`. According to `ci.adoptopenjdk.net`, it only has one executor, so I would suppose it's a different machine to the one that caused the issue to open initially. 

The particular command it's failing on is: 
```
security unlock-keychain -p `cat ~/.password`
```
However, the correct syntax for `unlock-keychain` is as follows:  `Usage: unlock-keychain [-u] [-p password] [keychain]`
When the keychain isn't specified (or passed `NULL`), it attempts to unlock the system keychain (See : https://developer.apple.com/documentation/security/1400341-seckeychainunlock?preferredLanguage=occ ), which the Jenkins user password is not the correct one. 
I was able to do the following as the Jenkins user without error, so I believe the keychain needs to be specified.
```
security unlock-keychain -p `cat ~/.password` login.keychain-db
```
This, however, doesn't explain why a restart fixes the issue or why it stops working after awhile.

**Comment by Willsparker** [comment] 2020-09-09 10:14
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_mac/4628/console
The above PRs seemed to have fixed the keychain issue, so closing the issue.

**Closed by Willsparker** 2020-09-09 10:14 UTC
Labels: bug
