### ISSUE TITLE
Test failing only at adopt: java/net/SocketImpl/BadUsages.java

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-infrastructure#897] opened 2019-08-14 12:46 UTC
Test: https://github.com/ibmruntimes/openj9-openjdk-jdk13/blob/openj9/test/jdk/java/net/SocketImpl/BadUsages.java
Build: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/91/
- Test is failing at adopt jenkins on jdk13 openj9 and hotspot builds on linux and intermittently on p linux. Passes fine when recreated on our intranet's jenkins and locally with the same builds.
- The failing test is called testConnect3() which creates a socket:
`var remote = new InetSocketAddress("blah-blah.blah-blah", 80);`
and then connects to it: ` impl.connect(remote, 0)`
expecting an IOException but does not throw one.

Error:
```
11:34:28  test BadUsages.testConnect3(): failure
11:34:28  java.lang.AssertionError: Expected IOException to be thrown, but nothing was thrown
11:34:28  	at org.testng.Assert.expectThrows(Assert.java:1018)
11:34:28  	at BadUsages.testConnect3(BadUsages.java:113)
```

**Comment by sxa555** [comment] 2019-08-14 15:08
I've been able to replicate this on my RHEL7 laptop. Are you certain it's an adoptopenjdk issue as opposed to a Linux distribution issue? Do you have a passing run from RHEL/CentOS elsewhere?

**Comment by adam-thorpe** [comment] 2019-08-14 15:22
My linux distribution is ubuntu so could potentially be a CentOS/RHEL issue? But it was failing on ubuntu and debian machines at adopt

**Comment by sxa555** [comment] 2019-08-14 16:00
Suggest liaising with @Willsparker as he has an Ubuntu 16 VM on his laptop which I believes shows the failure, so should provide an opportunity to play "Spot The Difference" ;-)

**Comment by Willsparker** [comment] 2019-08-15 09:03
@adam-thorpe 
The output for the failing test on the Ubuntu1604:

```
vagrant@adoptopenjdkU16:/vagrant/openjdk-tests/TestConfig$ make _jdk_custom

Running make 4.1
set TEST_ROOT to /vagrant/openjdk-tests/TestConfig/..
set JDK_VERSION to 13
set JDK_IMPL to openj9
set JVM_VERSION to openjdk13-openj9
set JCL_VERSION to latest
set JAVA_HOME to /vagrant/jdk-13+30
set SPEC to linux_x86-64_cmprssptrs
Running jdk_custom ...
"/vagrant/jdk-13+30/bin/java" -version
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+30-201908140434)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-81195db9c, JRE 13 Linux amd64-64-Bit Compressed References 20190814_37 (JIT enabled, AOT enabled)
OpenJ9   - 81195db9c
OMR      - 6e99760b
JCL      - 2337332cb3 based on jdk-13+30)
make[1]: Entering directory '/vagrant/openjdk-tests'
make[2]: Entering directory '/vagrant/openjdk-tests/openjdk'

===============================================
Running test jdk_custom_0 ...
===============================================
jdk_custom_0 Start Time: Thu Aug 15 01:23:40 2019 Epoch Time (ms): 1565857420860
"/vagrant/jdk-13+30/bin/java" -Xshareclasses:destroyAll; "/vagrant/jdk-13+30/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";

Attempting to destroy all caches in cacheDir /home/vagrant/javasharedresources/

JVMSHRC806I Compressed references persistent shared cache "sharedcc_vagrant" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
JVMSHRC005I No shared class caches available
cache cleanup done
variation: NoOptions
JVM_OPTIONS: -Xcompressedrefs 
{ itercnt=1; \
mkdir -p "/vagrant/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15658574208494/jdk_custom_0"; \
cd "/vagrant/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15658574208494/jdk_custom_0"; \
"/vagrant/jdk-13+30/bin/java" -Xmx512m -jar "/vagrant/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk/jtreg/lib/jtreg.jar" \
-agentvm -a -ea -esa -v:fail,error,time,nopass -retain:fail,error,*.dmp,javacore.*,heapdump.*,*.trc -ignore:quiet -timeoutFactor:8 -xml:verify -concurrency:2 -vmoptions:"-Xmx512m -Xcompressedrefs " \
-w ""/vagrant/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15658574208494/jdk_custom_0"/work" \
-r "/vagrant/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk/report" \
-jdk:"/vagrant/jdk-13+30" \
"/vagrant/openjdk-tests/TestConfig/scripts/testKitGen/../../../openjdk/openjdk-jdk/test/jdk/kava/net/SocketImpl/BadUsages.java"; \
if [ $? -eq 0 ] ; then echo ""; echo "jdk_custom_0""_PASSED"; echo ""; cd /vagrant/openjdk-tests/TestConfig/scripts/testKitGen/../../..;  else echo ""; echo "jdk_custom_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/vagrant/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15658574208494/TestTargetResult";
Error: Cannot find file: /vagrant/openjdk-tests/TestConfig/scripts/testKitGen/../../../openjdk/openjdk-jdk/test/jdk/kava/net/SocketImpl/BadUsages.java

jdk_custom_0_FAILED

"/vagrant/jdk-13+30/bin/java" -Xshareclasses:destroyAll; "/vagrant/jdk-13+30/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";

Attempting to destroy all caches in cacheDir /home/vagrant/javasharedresources/

JVMSHRC806I Compressed references persistent shared cache "sharedcc_vagrant" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
JVMSHRC005I No shared class caches available
cache cleanup done
jdk_custom_0 Finish Time: Thu Aug 15 01:23:42 2019 Epoch Time (ms): 1565857422065
make[2]: Leaving directory '/vagrant/openjdk-tests/openjdk'
make[1]: Leaving directory '/vagrant/openjdk-tests'


TEST TARGETS SUMMARY
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
FAILED test targets:
	jdk_custom_0

TOTAL: 1   EXECUTED: 1   PASSED: 0   FAILED: 1   DISABLED: 0   SKIPPED: 0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

_jdk_custom done
```

**Comment by Willsparker** [comment] 2019-08-15 09:41
Output of failing Test:
```
make _jdk_custom

Running make 4.1
set TEST_ROOT to /vagrant/openj9-openjdk-jdk13/openjdk-tests/TestConfig/..
set JDK_VERSION to 13
set JDK_IMPL to openj9
set JVM_VERSION to openjdk13-openj9
set JCL_VERSION to latest
set JAVA_HOME to /vagrant/jdk-13+30
set SPEC to linux_x86-64_cmprssptrs
Running jdk_custom ...
"/vagrant/jdk-13+30/bin/java" -version
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+30-201908140434)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-81195db9c, JRE 13 Linux amd64-64-Bit Compressed References 20190814_37 (JIT enabled, AOT enabled)
OpenJ9   - 81195db9c
OMR      - 6e99760b
JCL      - 2337332cb3 based on jdk-13+30)

...

test BadUsages.testAccept1(): success
test BadUsages.testAccept2(): success
test BadUsages.testAccept3(): success
test BadUsages.testAccept4(): success
test BadUsages.testAccept5(): success
test BadUsages.testAccept6(): success
test BadUsages.testAvailable1(): success
test BadUsages.testAvailable2(): success
test BadUsages.testAvailable3(): success
test BadUsages.testBind1(): success
test BadUsages.testBind2(): success
test BadUsages.testBind3(): success
test BadUsages.testBind4(): success
test BadUsages.testConnect1(): success
test BadUsages.testConnect2(): success
test BadUsages.testConnect3(): failure
java.lang.AssertionError: Expected IOException to be thrown, but nothing was thrown
	at org.testng.Assert.expectThrows(Assert.java:1018)
	at BadUsages.testConnect3(BadUsages.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

...

===============================================
java/net/SocketImpl/BadUsages.java
Total tests run: 39, Failures: 1, Skips: 0
===============================================

...

TEST TARGETS SUMMARY
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
FAILED test targets:
	jdk_custom_0

TOTAL: 1   EXECUTED: 1   PASSED: 0   FAILED: 1   DISABLED: 0   SKIPPED: 0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```

**Comment by adam-thorpe** [comment] 2019-08-15 12:38
I've found a difference, this is part of the output from my local machine:
```
ant -f ./src/build_envInfo.xml -DTEST_JDK_HOME=/root/documents/jdk-13+30_j9_08-15/
Buildfile: /root/documents/openj9-openjdk-jdk13/openjdk-tests/TestConfig/src/build_envInfo.xml

build:

clean:
   [delete] Deleting: /root/documents/openj9-openjdk-jdk13/openjdk-tests/TestConfig/autoGenEnv.mk
   [delete] Deleting directory /root/documents/openj9-openjdk-jdk13/openjdk-tests/TestConfig/src/bin
   [delete] Deleting: /root/documents/openj9-openjdk-jdk13/openjdk-tests/TestConfig/src/EnvDetector.jar

init:
    [mkdir] Created dir: /root/documents/openj9-openjdk-jdk13/openjdk-tests/TestConfig/src/bin

compile:
     [echo] Ant version is Apache Ant(TM) version 1.9.6 compiled on July 20 2018
     [echo] ============COMPILER SETTINGS============
     [echo] ===fork:                         yes
     [echo] ===debug:                        on
    [javac] Compiling 3 source files to /root/documents/openj9-openjdk-jdk13/openjdk-tests/TestConfig/src/bin

dist:
      [jar] Building jar: /root/documents/openj9-openjdk-jdk13/openjdk-tests/TestConfig/src/EnvDetector.jar

run:
     [java] System.getProperty('os.name')=Linux
     [java] 
     [java] System.getProperty('os.arch')=amd64
     [java] 
     [java] System.getProperty('java.fullversion')=13+30-201908150448
     [java] JRE 13 Linux amd64-64-Bit Compressed References 20190815_39 (JIT enabled, AOT enabled)
     [java] OpenJ9   - 41360de87
     [java] OMR      - 6e99760b
     [java] JCL      - 2337332cb3 based on jdk-13+30
     [java] 
     [java] System.getProperty('sun.arch.data.model')=64
     [java] 
     [java] System.getProperty('java.vm.name')=Eclipse OpenJ9 VM
     [java] 
```
However on the failing adopt build:
`[java] System.getProperty('java.fullversion')=null`

Not sure if this is important or not, but on other passing adopt tests this property is filled as normal

**Comment by adam-thorpe** [comment] 2019-09-20 13:45
Test passes on test-scaleway-ubuntu1604-x64-1 at adopt. Can't see any differences between this machine and any of the others

**Comment by Haroon-Khel** [comment] 2020-01-03 16:40
@adam-thorpe Using your steps, i'm unable to reproduce the error. The test passes on some of the adopt debian and ubuntu (softlayer and packet) machines. It also passes on a fyre RHEL 7 machine.
Im unable to view your original grinder job, but do you know of any specific adopt machines on which it fails?

**Comment by adam-thorpe** [comment] 2020-01-06 10:40
This information may be outdated and fixed by the DNS configuration changes documented here https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/984. I'll run a quick grinder and have a look, it's strange that Stewart was able to recreate this problem locally as well if this is the case

**Comment by adam-thorpe** [comment] 2020-01-06 10:43
Grinder passed

**Comment by Haroon-Khel** [comment] 2020-01-06 15:06
The test passed on my Ubuntu 16 Fyre machine

**Comment by sxa555** [comment] 2020-01-06 17:21
OK Let's close this and we can re-open if it shows up again.

**Closed by sxa555** 2020-01-06 17:21 UTC
Labels: bug, testFail
