### ISSUE TITLE
AIX testcase dependency failure

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1104] opened 2020-01-20 10:09 UTC
Looks like C library depedency not right?
https://ci.adoptopenjdk.net/job/Test_openjdk13_j9_sanity.openjdk_ppc64_aix/2/console
```
20:56:40  libjvm.so preloadLibrary(/ramdisk0/build/workspace/Test_openjdk13_j9_sanity.system_ppc64_aix/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so): 	0509-022 Cannot load module /ramdisk0/build/workspace/Test_openjdk13_j9_sanity.system_ppc64_aix/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so.
20:56:40  	0509-150   Dependent module libc++.a(cxxabi_64.o) could not be loaded.
20:56:40  	0509-022 Cannot load module libc++.a(cxxabi_64.o).
20:56:40  	0509-026 System error: A file or directory in the path name does not exist.
```

**Comment by sxa555** [comment] 2020-01-20 15:28
I suspect this is caused by the fact we build JDK13 on AIX71TL5SP5 now and therefore it won't work on earlier releases with an earlier libc. Suggest running the testing on https://ci.adoptopenjdk.net/computer/build-ibm-ppc64-aix-71-1/ for now

**Comment by pshipton** [comment] 2020-01-21 13:14
The XL C/C++ Runtime for AIX, V16.1 needs to be installed. It's not caused by building on AIX71TL5SP5, it's caused by using xlc 16.

https://www.ibm.com/support/pages/xl-cc-runtime-aix-v16101-fix-pack-december-2018

**Comment by sxa555** [comment] 2020-01-22 18:09
Was going to close this but we should probably add the xlc16 runtime into the AIX playbooks so we can run the JDK13 tests on all of our machines.

**Comment by sxa555** [comment] 2020-01-28 23:25
Given that OpenJ9 no longer requires the later AIX to build JDK13, only the v16 compiler, perhaps we should switch back to building on the earlier AIX level and install xlc16 on those systems to resolve this

**Comment by pshipton** [comment] 2020-01-29 01:54
Even if you build on an earlier machine, it will still require the XL C/C++ Runtime for AIX, V16.1 in order to run.

**Comment by sxa555** [comment] 2020-02-17 14:55
xlc16 now on both build machines. Note that https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1146 is a dup of this

**Closed by sxa555** 2020-02-17 14:55 UTC
Labels: bug
