### ISSUE TITLE
Need access to an OSX build machine

### ISSUE THREAD

**Issue by Leonardo2718** [AdoptOpenJDK/openjdk-infrastructure#1362] opened 2020-06-03 14:09 UTC
I'm trying to debug https://github.com/eclipse/openj9/issues/9416 (https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/610/consoleFull) but I'm unable to reproduce the failure locally. So, I need access to an osx machine that can reproduce that failure.

**Comment by sxa** [comment] 2020-06-03 17:29
We have not seen that error since the build you reference on May 26. What do you need to do on the machine? Do you believe it's likely to be reproducible? Also https://github.com/eclipse/openj9/issues/9291 suggests it is visible on the OpenJ9 systems too so would it be easier to get access to a system there?

**Comment by Leonardo2718** [comment] 2020-06-03 18:59
I have not seen the failure in eclipse/openj9#9291 since that issue was opened (at this point, I'm not even sure if it's related). The issue seems to be highly intermittent and I've only seen it reproduced in the link I posted above. 

Essentially, I want to capture as much information as I can when the failure happens. At this point, I think the only way to do that is to continuously re-run the build until it fails. This is far from ideal since it's a build job and not a test. I completely understand if having me manually re-running that build on a machine is not feasible. I am going to continue pursuing other options as well, but it's likely going to take a lot of time.

One alternative that could help speed things up without requiring me to have direct access to a machine would be to save all build artifacts even when a build fails (I know it seems kind of silly to want an incomplete build but it would provide much of the information I need for debugging). I don't know enough about how the build jobs work to say if that's at all feasible.

**Comment by sxa** [comment] 2020-06-04 12:28
Assigning to @gdams who has the appropriate access. If we let you on it, we should try and temporarily disable it from jenkins while you do your testing

**Comment by gdams** [comment] 2020-06-04 12:32
to be clear we're talking about https://ci.adoptopenjdk.net/computer/build-macstadium-macos1014-x64-1/

**Comment by gdams** [comment] 2020-06-04 12:34
@Leonardo2718 which key do you want me to add? You have multiple ssh keys listed in https://github.com/Leonardo2718.keys

**Comment by Leonardo2718** [comment] 2020-06-04 13:20
@gdams 
> to be clear we're talking about https://ci.adoptopenjdk.net/computer/build-macstadium-macos1014-x64-1/

Correct.

>@Leonardo2718 which key do you want me to add? You have multiple ssh keys listed in https://github.com/Leonardo2718.keys

Please use

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC57yLQu/iLHjB8SHBUpAzJqp6FXQl6jRH61IEektY4aJRnucZVBcp35n1zAzCbFoI1Sc9XbmfA5Lwnjl3+mi4l6/UvUzbWI30/41h6cfQdD4F6l/F5B4CqWiKqdJUCo7I/8niZCkaWsMikBsUsNey47WSPkpZxZtyBHqPYq7xxSBt8ykdIjKrKdgOQLPhy9hHMClfydO1RKpS+wvqLpnzeZwXGpVtx6GLTJ4rLJrPUIdrchN2bET3FzJXRE/ut4ICiS/mJz0qHuppzmHwVicqWHNSCcA1Z0eA2fCtUKzu1qvDSNe4F5IC3OOY76huMwXEHeoqxhdxsIcubxfSlEJ1qbgVW6hw395VAgqeCT++7YW12HisIHqrFrJUa8uk9lgzW4ruyTr1gO8CgCMV/bJiT9R3IiWEz4jK06SNZYtCC8GYc0wAuPcbOijDcBE+y/huxSa+l6xw3gDFSvckEpcXwdSsryMsBMMbKhWl+FDcQVlozwTywJ7k71D3j2rLiYOPaVORj1LmBGhhXLO2vAf3AIV/l/2nr5ksZe3ik2tlTA2dEyXDe7ljNY4DVYHEyIZ34LLjGeO4oA6Wo+x0bVmn+ebb54ohDKGWzX3EAlOgYECG70axk270eg6pTbKLc99tPl4ADCAs/uD8keQB1MYrLQCD+iBZo7OV8MIb8k0pxZQ==
```

> If we let you on it, we should try and temporarily disable it from jenkins while you do your testing

Probably a good idea.

**Comment by sxa** [comment] 2020-06-11 14:32
ping @gdams - have you actioned this?

**Comment by Leonardo2718** [comment] 2020-06-25 15:09
@gdams ping?

**Comment by gdams** [comment] 2020-07-13 12:00
@Leonardo2718 apologies for the delay, key is added:

```bash
ssh administrator@208.83.1.170
```

**Comment by karianna** [comment] 2020-07-14 16:06
Do we keep this open until we revoke the temp access?

**Comment by sxa** [comment] 2020-07-14 16:52
> Do we keep this open until we revoke the temp access?

Generally yes so we remember to remove. If it's a permanent request for a new team member I'd close immediately on adding it.

**Comment by Leonardo2718** [comment] 2020-10-21 16:24
@sxa @gdams It looks it won't be possible for me to recover a core file from this machine so I no longer require access.

**Closed** 2020-10-21 21:27 UTC
Labels: Temp Infra Access
