### ISSUE TITLE
Offload jobs running on the jenkins master

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#819] opened 2019-07-09 10:37 UTC
As per discsussions in the #infrastructure slack channel yesterday, the `git-hg` jobs and some other things (along with the top level piplines) are currently running on the jenkins master. It is desirable mostly for reasons of disk space usage to offload this onto another server. We have created another server at godaddy and will migrate jobs where practical onto the other machine in order to reduce the usage of the jenkins CI server.

This task will also involve creating and executing the ansible playbooks for setting up this new system.

**Comment by sxa555** [comment] 2019-07-09 12:14
Machine defined and added to inventory file: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/817

**Comment by sxa555** [comment] 2019-07-09 17:55
Machine set up (playbook not 100% complete - private keys aren't being installed automatically but have been done manually)

Following jobs are running to test the process:
https://ci.adoptopenjdk.net/view/git-hg/job/git-hg/job/git-hg-jdk13u/21/
https://ci.adoptopenjdk.net/view/git-hg/job/git-hg/job/git-hg-jdk/14/

I did initially have a shot at copying the workspaces from the previous machines but [that didn't seem to work](https://ci.adoptopenjdk.net/view/git-hg/job/git-hg/job/git-hg-jdk/13/console), so I've cleared it out to let them try from scratch

**Comment by sxa555** [comment] 2019-07-10 01:05
`git-hg` requires a later git than the one supplied with ubuntu 16.04 (2.7.4) ... Somehow there is a git package on the CI master which is 2.22 - origin unclear.

I have install `gcc`, `zlib1g-dev`, `libcurl4-openssl-dev` and `gettext` (for `msgfmt`) in order to compile git 2.22 from source (Unclear whether 2.15 would be ok - that's the version we install on most build machines at present

**Comment by sxa555** [comment] 2019-07-10 09:10
jenkins needs the following set, otherwise git client won't push back:
```
git config --global user.name "AdoptOpenJDK Github Bot"
git config --global user.email "adoptopenjdk+githubbot@gmail.com"
```
Also, process appears ok with git 2.15.0 so we can use the version that's in the playbooks (subject to the prerequisites that are listed in the previous comment.

**Comment by sxa555** [comment] 2019-07-10 09:18
11u ran ok seeded from a workspace copied from |CI master yesterday: https://ci.adoptopenjdk.net/job/git-hg/job/git-hg-jdk11u/320/console
12u now running with an empty initial workspace at https://ci.adoptopenjdk.net/job/git-hg/job/git-hg-jdk12u/164/ so that will take a few hours to complete.
8u running at https://ci.adoptopenjdk.net/job/git-hg/job/git-hg-jdk8u/377

**Comment by sxa555** [comment] 2019-07-11 12:28
AArch64 arm repository is possibly not working properly with the existing scripts

**Comment by sxa555** [comment] 2019-07-11 13:14
jdk8u job appears to have hung - aborted it and running again (after cleaning the workspace to ensure no corrupt data gets in the way)

**Comment by gdams** [comment] 2019-07-15 11:41
I've added the tags `linux`, `x64` and `hg`

**Comment by gdams** [comment] 2019-07-15 11:44
installed `unzip`

**Comment by sxa555** [comment] 2019-07-15 16:28
See also #822

**Comment by sxa555** [comment] 2019-07-17 10:10
The additional prereqs mentioned by @gdams are for the following jobs which have also been migrated from running on our now-defunct cloudcone server onto the new machine:
- jtreg (https://ci.adoptopenjdk.net/job/jtreg/)
- jemmy (https://ci.adoptopenjdk.net/job/jemmy/)
- jtharness (https://ci.adoptopenjdk.net/job/jtharness/)

**Comment by karianna** [comment] 2019-08-24 06:25
> The additional prereqs mentioned by @gdams are for the following jobs which have also been migrated from running on our now-defunct cloudcone server onto the new machine:
> 
> * jtreg (https://ci.adoptopenjdk.net/job/jtreg/)
> * jemmy (https://ci.adoptopenjdk.net/job/jemmy/)
> * jtharness (https://ci.adoptopenjdk.net/job/jtharness/)

These were still labeled incorrectly, now fixed.

I *think* tha's it - @sxa555 Can we close this?

**Comment by sxa555** [comment] 2019-08-26 18:19
@karianna I'm holding this open until the playbooks are finalised and tested. Hopefully will get through that with Will this week.

**Comment by sxa555** [comment] 2019-12-23 13:46
This machine now also needs JDK11 installed as per the problems described in https://github.com/AdoptOpenJDK/openjdk-build/issues/1445

We also still have the `hg` tag on the master node, so I'm going to remove them to force all related jobs onto the other machine (especially since master doesn't have JDK11 in the right place)

**Comment by Haroon-Khel** [comment] 2020-01-28 15:03
The playbook I've created for this task is more or less complete. There's just a few complications. 

- The Jemmy build job requires apache-maven-3.5.3 to be installed on the machine. The machine on which this job usually runs, 160.153.247.225, has it installed in `tools/hudson.tasks.Maven_MavenInstallation/apache-maven-3.5.3/`, but I have reason to suspect that this installation was done automatically by Jenkins. Can anyone confirm this? Because if this is the case, then I do not need to include a maven installation task in the playbook.

- The Jtreg job requires `$JAVA_HOME` to point to a java of atleast 8 (I think). Again, I suspect that Jenkins takes care of this on its own, but I need this confirmed.

@gdams @karianna Thoughts?

**Comment by sxa555** [comment] 2020-02-25 19:21
Would be good to clear this one off the books. @Haroon-Khel No I don't believe `JAVA_HOME` can be guaranteed to be set automatically, although we could add it to the jenkins machine definition to make it take effect.

I suspect you're right about the maven installation directory, and while I'm a little reluctant to fully rely on that path we could use that one - @karianna would you be ok with that?

@Haroon-Khel is the playbook you had in progress in as a PR anywhere yet or still waiting the conclusion of the above discussions?

**Comment by Haroon-Khel** [comment] 2020-02-26 10:30
@sxa555 I was waiting for answers to my above comment before making a pr, but ill just put it in now for review

**Closed** 2020-02-27 19:00 UTC
Labels: ansible
