### ISSUE TITLE
Windows machines permission denied /etc/gitconfig

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1732] opened 2020-12-03 08:54 UTC
```
05:01:05  getOpenjdk:
05:01:05       [exec] error: could not lock config file /etc/gitconfig: Permission denied
05:01:05       [exec] Result: 255
05:01:05       [echo]  Using user specified repo and branch
05:01:05       [echo] git clone --depth 1 -q -b openj9 https://github.com/ibmruntimes/openj9-openjdk-jdk16 openjdktemp
```
Various nodes:
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows_xl/8/
test-aws-win2019-x64-2
test-godaddy-win2016-x64-4
test-godaddy-win2016-x64-2

**Comment by andrew-m-leonard** [comment] 2020-12-03 09:02
Is there a ansible setup issue for these machines?

**Comment by Willsparker** [comment] 2020-12-03 11:26
Do you know the command that's being run?

We _do_ change the Git config as part of the installation, via a properties file (https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/4d3275f2ed4232ba1a4b53f452d10d256f8ad563/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/GIT/tasks/main.yml#L27)

On `test-godaddy-win2016-x4-4`, I get the permission is denied error as the Jenkins user when running `touch /etc/gitconfig` - this is due to not having write access to the `/etc` folder - however, the file isn't actually there to begin with. 

On `test-aws-win2019-x64-2`, the file is there, and I'm able to run `touch /etc/gitconfig` as admin, but again, not as `Jenkins`. So I suspect this is just an perms issue.

On the `test-aws-win2019-x64-2` machine:
![image](https://user-images.githubusercontent.com/52783864/101010028-16c0e080-355a-11eb-84e7-b98c3e2479da.png)
In `File Explorer`, 'Everyone' has read access, but only Administrator has read, write and 'special permissions'.

**Comment by Willsparker** [comment] 2020-12-07 10:34
The command being run is (most likely) this: https://github.com/AdoptOpenJDK/openjdk-tests/blob/afaba1c2eade4723cb6f3e39ddec778048803279/openjdk/build.xml#L86

Which further suggests it's just a perms thing. 
Just running `chown jenkins /etc/gitconfig` allows the file to be edited by the jenkins user, however the command still fails when running manually- which makes me think this is looking at a different config file (as system ones, I believe are separate from global ones)

**Comment by Willsparker** [comment] 2020-12-07 10:54
Okay, so, I think the issue is that the Jenkins user can't create the lock-file in the `/etc` directory. The `git config --system` commands are only really meant to be executed by the Administrator, anyway - does the command really need to be for `--system` ? I wouldn't want to make it default for `/etc` to be accessible for the Jenkins user. 

The command `git config --global core.longpaths true` works, and puts a new config file in `/home/jenkins/.gitconfig`, where it's guaranteed to be accessible

**Comment by smlambert** [comment] 2020-12-07 19:27
Thanks for locating this @Willsparker !  Created https://github.com/AdoptOpenJDK/openjdk-tests/issues/2094 to address it

**Comment by Willsparker** [comment] 2020-12-11 09:41
Ref: https://github.com/AdoptOpenJDK/openjdk-tests/pull/2101
PR has been put in, closing issue :-)

**Closed by Willsparker** 2020-12-11 09:41 UTC
Labels: ansible
