### ISSUE TITLE
Ansible request for CentOS6 SCL

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1770] opened 2020-12-18 16:59 UTC
May just need changing to `vault` as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1765 although @Willsparker was there a reason your first change wasn't made in the playbooks?
```
 TASK [Common : Install CentOS SCL x86_64 repo for gcc7.3] **********************
changed: [localhost]

TASK [Common : Install additional build tools for CentOS on x86] ***************
failed: [localhost] (item=glibc.i686) => {"ansible_loop_var": "item", "changed": false, "item": "glibc.i686", "msg": "Error: Cannot find a valid baseurl for repo: centos-sclo-rh\n", "rc": 1, "results": []}
failed: [localhost] (item=glibc-devel.i686) => {"ansible_loop_var": "item", "changed": false, "item": "glibc-devel.i686", "msg": "Error: Cannot find a valid baseurl for repo: centos-sclo-rh\n", "rc": 1, "results": []}
failed: [localhost] (item=libstdc++.i686) => {"ansible_loop_var": "item", "changed": false, "item": "libstdc++.i686", "msg": "Error: Cannot find a valid baseurl for repo: centos-sclo-rh\n", "rc": 1, "results": []}

PLAY RECAP *********************************************************************
```

**Comment by Willsparker** [comment] 2020-12-18 18:21
dupe of #1745  , so I'm going to close.

> May just need changing to vault as per #1765 although @Willsparker was there a reason your first change wasn't made in the playbooks?

The Vagrantfiles install `libselinux-python` in the provisioning script, so it needs to have it's repos fixed before that. That package needs to be installed to do [this task](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/2aa951ac4592452b943d74511d70d16e27b531ee/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml#L71) (See https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=CentOS6,label=vagrant/957/console) which is run before installing the OS build packages. I'd rather not have that task (and one to separately install `libselinux-python` ) in the `Common/main.yml` file, as if we start putting CentOS6 specific tasks in there, it will start getting messy.

**Closed by Willsparker** 2020-12-18 18:21 UTC
Labels: ansible

**Comment by sxa** [comment] 2020-12-18 20:19
I kept this one separately so we can close it if we can work around it ourselves and then close the other one once the upstream issues is correct (assuming it will be ... it may not) ... but ok we can progress it in there

**Comment by sxa** [comment] 2020-12-18 20:21
>  if we start putting CentOS6 specific tasks in there, it will start getting messy.

Yes, but it's also our primary xLinux build environment, and it will just fail outside VPC/Docker just now if anyone tries to run it without giving them any idea how to resolve it

**Comment by Willsparker** [comment] 2020-12-19 13:43
> once the upstream issues is correct

https://wiki.centos.org/About/Product ; CentOS6 has reached the end of it's life; I assume the repo changes are reflecting that?

> also our primary xLinux build environment

Is CentOS6 reaching EOL going to change or affect that in any way ...? If not, yeah, it certainly should be put in the playbook, though I may opt to create a new separate role that goes before Common that is only run on CentOS6, to keep it cleaner.

**Comment by aahlenst** [comment] 2020-12-19 14:53
> Is CentOS6 reaching EOL going to change or affect that in any way ...?

That's hard to say. Currently, there's still demand for glibc 2.12 compatibility. Azul even provides glibc 2.5 compatibility. OpenJDK recommends building on Oracle Linux 7 with an Oracle Linux 6 sysroot. Effectively, that's not much different than what we do: Building in a CentOS 6 container with an upgraded GCC (our approach is simpler with our build scripts). I don't see us moving away from glibc 2.12 as long as OpenJDK supports it.

**Comment by Willsparker** [comment] 2020-12-19 20:01
That's a fair argument - I'll get it working from the playbooks then ! :-)
