### ISSUE TITLE
jenkins: Add ability to let more users view the jenkins job configurations

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#27] opened 2017-10-02 15:20 UTC
I've had a few people as if they can see the job configuration to be able to understand what the jobs are doing. While jenkins doesn't have any integrated ability to allow read-only access (aso by default if you can view it you edit it) there are plugins such as https://wiki.jenkins.io/display/JENKINS/Extended+Read+Permission+Plugin which will change that. opening this issue for discussion to see if there is any reason not to have this in place - do we have sensitive stuff in the jobs that wouldn't be hidden by this plugin?

**Comment by gdams** [comment] 2017-10-03 11:37
I'm happy to have this discussion, there are certain jobs where we definitely do not want users viewing the job configuration but we can override the matrix when this is required. No objections from me.... CC @AdoptOpenJDK/getopenjdk

**Comment by gdams** [comment] 2017-11-22 01:13
closing as a duplicate of #40

**Closed by gdams** 2017-11-22 01:13 UTC
Labels: enhancement, Jenkins
