### ISSUE TITLE
build failure : Can not access tar.gz.

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1412] opened 2020-06-25 08:45 UTC
**jdk11u-windows-x64-hotspot
jdk11u-windows-x64-openj9**

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/644/console

ls: cannot access 'workspace/target/*.tar.gz': No such file or directory

**Comment by M-Davies** [comment] 2020-06-25 08:52
@archanaNogriya Looks like it's actually a copy artefact failure. Not due to a `No such file or directory`
```
02:49:15  Copied 0 artifacts from "build-scripts » release » create_installer_windows" build number 5115
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
02:49:15  Execution error: null
```

**Comment by archanaNogriya** [comment] 2020-06-25 09:04
thanks, @M-Davies, I understood that copy artefact failure was due to not able to access the file.

**Comment by adamfarley** [comment] 2020-06-25 15:02
I suggest that there are two bugs in this job.

The workspace issue should be fixed, I agree, but I believe that the failure is being caused by something in the installer job, as Morgan mentioned.

Keep this issue for the "cannot access workspace" problem. I'll raise a new one for the installer once I get access to it.

**Comment by M-Davies** [comment] 2020-06-25 15:05
Please close as a dup of https://github.com/AdoptOpenJDK/openjdk-build/issues/1834. The error message is misleading due to https://github.com/AdoptOpenJDK/openjdk-build/pull/1932

**Closed** 2020-06-25 16:34 UTC
Labels: bug, duplicate
