### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space on s390 systemtest builds 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-infrastructure#542] opened 2018-10-22 15:08 UTC
[openjdk8_hs_systemtest_s390x_linux](
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_hs_systemtest_s390x_linux/) build is failing consistently with a `java.lang.OutOfMemoryError Java heap space` - error on the following two machines:

**build-marist-ubuntu1604-s390x-2**
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_hs_systemtest_s390x_linux/91/console
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_hs_systemtest_s390x_linux/92/console
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_hs_systemtest_s390x_linux/95/console

**test-marist-ubuntu1604-s390x-1**
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_hs_systemtest_s390x_linux/93/console

**Error**

````
06:24:59     [javac] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
06:24:59     [javac] 	at java.util.HashMap.newNode(HashMap.java:1750)
06:24:59     [javac] 	at java.util.HashMap.putVal(HashMap.java:642)
06:24:59     [javac] 	at java.util.HashMap.put(HashMap.java:612)
06:24:59     [javac] 	at java.util.ListResourceBundle.loadLookup(ListResourceBundle.java:204)
06:24:59     [javac] 	at java.util.ListResourceBundle.handleGetObject(ListResourceBundle.java:130)
06:24:59     [javac] 	at java.util.ResourceBundle.getObject(ResourceBundle.java:441)
06:24:59     [javac] 	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
06:24:59     [javac] 	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:190)
06:24:59     [javac] 	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:141)
06:24:59     [javac] 	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:135)
06:24:59     [javac] 	at com.sun.tools.javac.util.Log.localize(Log.java:684)
06:24:59     [javac] 	at com.sun.tools.javac.util.Log.printLines(Log.java:497)
06:24:59     [javac] 	at com.sun.tools.javac.main.Main.resourceMessage(Main.java:610)
06:24:59     [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:543)
06:24:59     [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:381)
06:24:59     [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:370)
06:24:59     [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:361)
06:24:59     [javac] 	at com.sun.tools.javac.Main.compile(Main.java:56)
06:24:59     [javac] 	at com.sun.tools.javac.Main.main(Main.java:42)
```

**Comment by Mesbah-Alam** [comment] 2018-10-22 15:09
FYI @sxa555

**Comment by sxa555** [comment] 2018-10-30 09:16
When did this start failing? It looks like it ran through with warnings a few weeks ago. an we retry an old build and understand if it's something that has changed in the JVM or if we do really need to take action on the machine? Has it been failing with both HotSpot and OpenJ9 VMs?

Both machines have 8Gb of RAM. The `test-` machine has 10Gb of swap, the `build-` machine (where it last seemed to run through ok) has 2Gb of swap.

Simon, should 8Gb of RAM be adequate for running the systemtest suites?

**Comment by sxa555** [comment] 2018-11-06 11:41
Just asked lumpfish and he confirmed that should be an adequate amount of RAM :-)

**Comment by sxa555** [comment] 2019-03-07 17:20
@Mesbah-Alam What's the current status of this - still a problem?

**Comment by sxa555** [comment] 2019-04-26 14:56
@Mesbah-Alam Closing for now - if it's still an issue please re-open

**Closed by sxa555** 2019-04-26 14:56 UTC
Labels: bug
