### ISSUE TITLE
System unavailable: https://ci.adoptopenjdk.net/computer/build-alibaba-win2012r2-x64-1/

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1821] opened 2021-01-08 07:45 UTC
https://ci.adoptopenjdk.net/computer/build-alibaba-win2012r2-x64-1/
is down

**Comment by sxa** [comment] 2021-01-08 08:27
Duplicate of #1818

**Closed** 2021-01-08 08:27 UTC
Labels: systemdown
