### ISSUE TITLE
System unavailable: https://ci.adoptopenjdk.net/computer/test-gdams-debian10-riscv64-1/

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2113] opened 2021-04-09 12:37 UTC
Riscv64 machine used to build bisheng is continually unavailable : 
  https://ci.adoptopenjdk.net/computer/test-gdams-debian10-riscv64-1
We need to find a more reliable machine to use for this build.

**Comment by sxa** [comment] 2021-04-11 10:16
Duplicate of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1904

**Closed** 2021-04-11 10:16 UTC
Labels: systemdown
