### ISSUE TITLE
build-ibmcloud-win2012r2-x64-1 windows installer WIX setup issue

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1969] opened 2021-02-23 08:53 UTC
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/12540/console
```
Generate OpenJDK setup "hotspot" for "x86-32" platform "jre"
****************************************************
looking for .\SourceDir\OpenJDK16\hotspot\x86-32\jdk-16.0.0-jre
looking for .\SourceDir\OpenJDK16\hotspot\x86-32\jdk16u0-b36-jre
looking for .\SourceDir\OpenJDK16\hotspot\x86-32\jdk-16+36-jre
Source dir used : .\SourceDir\OpenJDK16\hotspot\x86-32\jdk-16+36-jre
PRODUCT_ID: {118F461A-E6AC-4E8F-842E-9C1A5E5A1673}
SOURCE_TEXT_GUID (without displaying secret UPGRADE_CODE_SEED) : jre-16-x86-hotspot
Constant PRODUCT_UPGRADE_CODE: {D4DE1BEB-FE87-5EF0-CA73-4835CAD73344}
copy "Main.hotspot.wxs"
        1 file(s) copied.
HEAT

E:\workspace\build-scripts\release\create_installer_windows\wix>"!WIX!bin\heat.exe" dir "!REPRO_DIR!" -out Files-!OUTPUT_BASE_FILENAME!.wxs -gg -sfrag -scom -sreg -srd -ke -cg "AppFiles" -var var.ProductMajorVersion -var var.ProductMinorVersion -var var.ProductVersionString -var var.MSIProductVersion -var var.ReproDir -dr INSTALLDIR -platform !PLATFORM! 
The system cannot find the path specified.

E:\workspace\build-scripts\release\create_installer_windows\wix>IF ERRORLEVEL 1 (
ECHO Failed to generating Windows Installer XML Source files (.wxs)  
 GOTO FAILED 
) 
Failed to generating Windows Installer XML Source files (.wxs)

E:\workspace\build-scripts\release\create_installer_windows\wix>EXIT /b 2 

E:\workspace\build-scripts\release\create_installer_windows\wix>exit 2 
```
From Philippe:  WIX is probably not located as usual

**Comment by Willsparker** [comment] 2021-02-23 08:56
Dupe of #1950 (sort of) - I already mentioned the issue there, and I'll post updates in there.

**Closed by Willsparker** 2021-02-23 08:56 UTC
Labels: ansible
