### ISSUE TITLE
build-scaleway-ubuntu1604-armv7-1 connection issue

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1358] opened 2020-06-03 10:02 UTC
Build job hung, looks like connectivity problem:

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-linux-arm-hotspot/97/console

22:17:34  Cannot contact build-scaleway-ubuntu1604-armv7-1: java.lang.InterruptedException

**Comment by Haroon-Khel** [comment] 2020-06-03 11:31
Duplicate of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1357

**Closed by Haroon-Khel** 2020-06-03 11:31 UTC
