### ISSUE TITLE
CentOS6 PR check failing

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1880] opened 2021-02-01 13:45 UTC
CentOS6 checks do not work. This will presumably stop the updating of the build docker images, therefore updates such as #1706 will not take effect

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1870/checks?check_run_id=1804791275

```
TASK [adoptopenjdk_install : Check if jdk-8 is already installed in the target location] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "ls -ld /usr/lib/jvm/jdk8* >/dev/null 2>&1", "delta": "0:00:00.542578", "end": "2021-02-01 08:05:18.364486", "msg": "non-zero return code", "rc": 2, "start": "2021-02-01 08:05:17.821908", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

TASK [adoptopenjdk_install : Install latest release if one not already installed] ***
FAILED - RETRYING: Install latest release if one not already installed (3 retries left).
FAILED - RETRYING: Install latest release if one not already installed (2 retries left).
FAILED - RETRYING: Install latest release if one not already installed (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "Failed to validate the SSL certificate for github-releases.githubusercontent.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.6.6 (r266:84292, Jun 20 2019, 14:14:55) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]) or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: hostname 'github-releases.githubusercontent.com' doesn't match either of '*.githubassets.com', 'githubassets.com'.", "status": -1, "url": "https://api.adoptopenjdk.net/v3/binary/latest/8/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk"}

PLAY RECAP *********************************************************************
localhost                  : ok=112  changed=72   unreachable=0    failed=1    skipped=62   rescued=0    ignored=9 
```

**Comment by Willsparker** [comment] 2021-02-02 07:26
Duplicate of #1877

**Closed by Willsparker** 2021-02-02 07:26 UTC
Labels: ansible, bug, critical
