### ISSUE TITLE
System unavailable: build-scaleway-ubuntu1604-x64-1 out of disk space

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1658] opened 2020-11-02 09:36 UTC
build-scaleway-ubuntu1604-x64-1

https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_linux/20437/console

create_installer_linux failing due to apparent "out of disk space", however the node seems to have plenty on volume /home, so something a miss somewhere...?

**Comment by sxa** [comment] 2020-11-02 11:56
Machine had ran out of inodes due to lots of files in `/tmp`. @Willsparker is clearing it up:
```
root@build-scaleway-ubuntu1604-x64-2:/tmp# df -i
Filesystem             Inodes   IUsed   IFree IUse% Mounted on
none                  1019995    1335 1018660    1% /dev
tmpfs                 1021046    1540 1019506    1% /run
/dev/vda              3055616 3055616       0  100% /
tmpfs                 1021046      92 1020954    1% /dev/shm
tmpfs                 1021046       4 1021042    1% /run/lock
tmpfs                 1021046      13 1021033    1% /sys/fs/cgroup
/dev/mapper/vg00-home 6553600 1083937 5469663   17% /home
tmpfs                 1021046       6 1021040    1% /run/user/1000
tmpfs                 1021046       4 1021042    1% /run/user/1001
```

**Comment by Willsparker** [comment] 2020-11-02 12:13
the `/tmp` folder was full of `.png`s and `baseline*` directories, that was owned and created by Jenkins. I cleared those up, and we're currently sitting on about `5800` free inodes - though that seems quite little, extracting the JDK appears to only take about 600, so this should be fine. Closing

**Comment by sxa** [comment] 2020-11-02 12:51
5800 is nowhere near fine. The problem is caused by nearly 3 million inodes being used up by `/tmp/.gradle-test-kit-jenkins` - specifically over 56000 directories under `caches/6.1/scripts` in there.

**Comment by sxa** [comment] 2020-11-02 12:52
I've deleted 50K of them but we'll need to stop it creating so many

**Comment by sxa** [comment] 2020-11-02 13:21
Also lots (~100,000) in `/tmp/.gradle-test-kit-jenkins/caches/6.1/scripts-remapped`

**Comment by sxa** [comment] 2020-11-02 14:00
Created separate issue in the installer repository to produce a permanent solution. I have removed a few tens of thousands of directories from the `scripts-remapped` directory for now which will give us a bit of leaway until we have a proper solution.

**Closed by sxa** 2020-11-02 14:00 UTC
Labels: systemdown
