### ISSUE TITLE
build-osuosl-ppc64-aix-71-2 was marked offline: Connection was broken: java.io.IOException: Unexpected EOF

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1280] opened 2020-04-15 10:19 UTC
AIX builds are failing at the end with messages like
```
build-osuosl-ppc64-aix-71-2 was marked offline: Connection was broken: java.io.IOException: Unexpected EOF
	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:99)
	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63
```
This is happening with builds on both build-osuosl-ppc64-aix-71-1 and  build-osuosl-ppc64-aix-71-2.

Examples:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/613
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/615

**Comment by Willsparker** [comment] 2020-04-15 10:22
Duplicate of #1279 , Closing

**Closed by Willsparker** 2020-04-15 10:22 UTC
