### ISSUE TITLE
test-azure-win2012r2-x64-2 performing VERY slowly...?

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1939] opened 2021-02-17 07:17 UTC
Node test-azure-win2012r2-x64-2 recently has started to run test jobs very slowly:
https://ci.adoptopenjdk.net/job/Test_openjdk17_j9_extended.functional_x86-64_windows_xl/27/consoleFull aborted after 10hours running, should normally take 2hours
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.openjdk_x86-32_windows/23/console still running after 6hours, normally takes <1hour

**Comment by Willsparker** [comment] 2021-02-17 09:14
On the machine, there's a process called `revokeall (32-bit)` and a `touch` process that is pinning the CPU at 100%.  The test you listed is still running, so I presume it's that. It looks like that test has hung (last update was at 07:49:56). At what point do we usually stop the test?

**Comment by sxa** [comment] 2021-02-17 10:53
I've terminated those two processes - we'll see if it recurs since touch in particular is not normally a utility that should chew much in the way of CPU

**Comment by sxa** [comment] 2021-02-17 11:18
As agreed elsewhere, @andrew-m-leonard will now run some tests to see if the machine is still running slow and whether those processes come back to cause more problems

**Comment by sxa** [comment] 2021-02-18 10:16
@andrew-m-leonard Has confirmed that machines are not being held up on this machine, therefore closing.

**Closed** 2021-02-18 11:37 UTC
Labels: Infra Machine issue, windows
