### ISSUE TITLE
jdk8u-solaris-sparcv9-hotspot: openssl: command not found

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1724] opened 2020-11-30 08:53 UTC
Machine: build-inspira-solaris10u11-sparcv9-2
```
19:38:07  Done (138 CA certs processed, 29 skipped).
19:38:07  ./mk-cacerts.sh: line 73: openssl: command not found
```
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-hotspot/372/console

**Comment by aahlenst** [comment] 2020-11-30 09:42
Duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/2265.

**Closed** 2020-11-30 10:08 UTC
Labels: ansible, duplicate
