### ISSUE TITLE
Create missing Ansible playbooks - Mac OS

### ISSUE THREAD

**Issue by bblondin** [AdoptOpenJDK/openjdk-infrastructure#212] opened 2018-02-13 16:13 UTC
Ref: #6 

We currently don't have a playbooks for Mac OS

Its more important to get a playbook working on this platform first then we can work on incorporating it into the greater main playbooks

**Comment by gdams** [comment] 2018-02-13 22:48
I'm happy to work on this, I might request an extra mac to test the playbook on.

**Comment by jdekonin** [comment] 2018-02-14 22:48
Not that the entire playbook is of use.  But I found homebrew and a very few extras enabled me to compile on my macbook pro.  "Testing the Playbook" section might be of value.

https://github.com/geerlingguy/mac-dev-playbook

**Comment by sxa555** [comment] 2018-11-19 18:35
From @jdekonin Please make sure curl is also included in the playbook as per #404.

**Comment by jdekonin** [comment] 2018-11-26 17:37
As notes in https://github.com/eclipse/openj9/issues/3790 when running openjdk-tests there setup requirements on the system.
```
vi /etc/sysctl.conf
kern.sysv.shmmax=314572800
kern.sysv.shmall=76800
```

**Comment by sxa555** [comment] 2018-11-29 18:33
@cwillheim Are you able to progress this? Any current blockers?

**Comment by cwillhelm** [comment] 2018-11-29 18:37
No current blockers other than some stuff that has to be done from the GUI. I also need a Mac for testing, unfortunately the one we are using is OSX 10.10, and can't be upgraded to 10.11 or beyond. Not sure how big of an impact that will have.

It's still a work in progress though, I'm putting everything in a single playbook file first, and will separate out the other aspects (like CPAN, Freemarker, etc) once it's confirmed to be working.

**Comment by sxa555** [comment] 2018-11-29 19:19
Out existing machines at adoptopenjdk are all 10.10 so that version is fine by me for the purposes of this ;-)
Which things need to be installed via the GUI?

Please provide updates in this work item since sharing a log of what we've tried and got working / failed to get working is always useful. We do of course have the work in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/219/files to base from.

**Comment by cwillhelm** [comment] 2018-11-29 19:36
For the GUI stuff,

```
System Preferences -> Sharing

    Turn On Screen Sharing, allow access for Adminstrators (default)
    Turn On Remote Login, allow access for Adminstrators (default)

System Preferences -> Sharing

    Turn On Remote Login, allow access for jenkins

test it out
ssh jenkins@machine name
```

I'll keep you posted about what has and hasn't worked soon, just making a fresh image of this mac for testing.

**Comment by cwillhelm** [comment] 2018-11-30 16:31
Very alpha version has been written, hasn't been tested yet. Will throw it towards a machine when I get the chance.

**Comment by sxa555** [comment] 2018-12-03 19:30
@cwillhelm Can you create a PR with what you've got, prefixed with [WIP] so we know it's incomplete? Would be best to have it in github even if it's not yet complete :-)

**Comment by cwillhelm** [comment] 2018-12-03 19:41
@sxa555 done, very rough -- it's currently about half functional (figuring out some git HTTPS issues @ line 268)

**Comment by cwillhelm** [comment] 2018-12-05 16:57
https://blog.bearandgiraffe.com/ansible-github-and-a-failed-to-validate-the-ssl-certificate-story-a8a10ea17512

There's some weird issues specifically related to Ansible, Git, Python, and MacOS that causes certificates issues with Github (since they reject TLS 1.1 connections). Based on my findings and these fixes (which apply to MacOS 10.12+) we may have to mirror the jdk files to a different repository in order to properly download them on MacOS 10.10. I'm going to do some investigation to see if this _does_ in fact work on 10.12+, but in the meantime that's the current blocker on where we are at with the playbook.

I tried the solutions in the above link, as well as some other ones on the internet and did not have any success.

**Comment by sxa555** [comment] 2018-12-05 17:34
Hmmm that surprises me a little since the build machines at adoptopenjdk are all 10.10 and they do currently manage to pull frmo git without problems.

**Comment by jdekonin** [comment] 2019-01-25 00:00
https://github.com/eclipse/openj9/issues/4375 requests changes to the requirements on an OSX install.  Setting umask to `0002` and /etc/sysctl.conf values for
kern.sysv.shmmax=125839605760
kern.sysv.shmall=30722560

I attempted to use `launchctl config system umask 002` or `launchctl config user umask 002` as per apple documentation, but that didn't work for me.  I made the change within the jenkins user .bashrc `umask 0002` which did work.

**Comment by jdekonin** [comment] 2019-01-31 13:43
Taken from discussion with @cwillhelm, `pmset -a sleep 0` might be of use in stopping the mac from going to sleep and becoming disabled in jenkins.

**Comment by sxa555** [comment] 2019-03-08 11:24
@gdams Ref the work you did to set up a 10.12 box for https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/711, what needed to be done manually over and above the playbook execution? I know you mentioned the extra boot JDK but I'm guessing there was probably more manual steps required? Would be good to have the current state documented here.

**Comment by gdams** [comment] 2019-07-30 09:22
playbook merged

**Closed by gdams** 2019-07-30 09:22 UTC
Labels: ansible, help wanted
